default_agent: job_market_agent
agents:
  agentcore_starter_strands:
    name: agentcore_starter_strands
    entrypoint: /Users/subiksha/Desktop/Semester 1/aws-hackathon/agentcore_starter_strands.py
    platform: linux/arm64
    container_runtime: none
    source_path: /Users/subiksha/Desktop/Semester 1/aws-hackathon
    aws:
      execution_role: arn:aws:iam::746630811346:role/AmazonBedrockAgentCoreSDKRuntime-us-east-2-9c0804ec0c
      execution_role_auto_create: false
      account: '746630811346'
      region: us-east-2
      ecr_repository: 746630811346.dkr.ecr.us-east-2.amazonaws.com/bedrock-agentcore-agentcore_starter_strands
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: agentcore_starter_strands-J372CJBJwP
      agent_arn: arn:aws:bedrock-agentcore:us-east-2:746630811346:runtime/agentcore_starter_strands-J372CJBJwP
      agent_session_id: 59464d3e-832f-4227-b9c7-661fc0d6bb10
    codebuild:
      project_name: bedrock-agentcore-agentcore_starter_strands-builder
      execution_role: arn:aws:iam::746630811346:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-2-9c0804ec0c
      source_bucket: bedrock-agentcore-codebuild-sources-746630811346-us-east-2
    memory:
      mode: STM_AND_LTM
      memory_id: agentcore_starter_strands_mem-1lk0rRBOY2
      memory_arn: arn:aws:bedrock-agentcore:us-east-2:746630811346:memory/agentcore_starter_strands_mem-1lk0rRBOY2
      memory_name: agentcore_starter_strands_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: false
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
  job_market_agent:
    name: job_market_agent
    entrypoint: /Users/subiksha/Desktop/Semester 1/aws-hackathon/job_market_agent.py
    platform: linux/arm64
    container_runtime: none
    source_path: /Users/subiksha/Desktop/Semester 1/aws-hackathon
    aws:
      execution_role: arn:aws:iam::746630811346:role/AmazonBedrockAgentCoreSDKRuntime-us-east-2-d71e2071cc
      execution_role_auto_create: false
      account: '746630811346'
      region: us-east-2
      ecr_repository: 746630811346.dkr.ecr.us-east-2.amazonaws.com/bedrock-agentcore-job_market_agent
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: job_market_agent-gmX7PL4YPu
      agent_arn: arn:aws:bedrock-agentcore:us-east-2:746630811346:runtime/job_market_agent-gmX7PL4YPu
      agent_session_id: a0efcc8e-7747-4934-8daa-d7e86d3569bc
    codebuild:
      project_name: bedrock-agentcore-job_market_agent-builder
      execution_role: arn:aws:iam::746630811346:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-2-d71e2071cc
      source_bucket: bedrock-agentcore-codebuild-sources-746630811346-us-east-2
    memory:
      mode: STM_ONLY
      memory_id: job_market_agent_mem-snoEAs4nej
      memory_arn: arn:aws:bedrock-agentcore:us-east-2:746630811346:memory/job_market_agent_mem-snoEAs4nej
      memory_name: job_market_agent_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
